### ISSUE TITLE
1.19.2 Crashing on startup

### ISSUE THREAD

**Issue by KallanX** [pg9182/northstar-dedicated#70] opened 2023-10-03 14:18 UTC
Just upgraded the server container to the newly released 1.19.2 and the server is in a crash loop.

~~~~~SNIP~~~~~
[14:14:55] [RPAK_FSYS] [info] LoadPakAsync common.rpak 1
[14:14:55] [RPAK_FSYS] [info] Not loading pak ./R2Northstar\mods\Northstar.Custom\paks\mp_weapon_shotgun_doublebarrel.rpak for dedicated server
[14:14:55] [RPAK_FSYS] [info] Not loading pak ui.rpak for dedicated server
[14:14:55] [RPAK_FSYS] [info] Not loading pak particle_scripts.rpak for dedicated server
[14:14:55] [RPAK_FSYS] [info] Not loading pak highlight.rpak for dedicated server
[14:14:55] [RPAK_FSYS] [info] Not loading pak mp_lobby.rpak for dedicated server
[14:14:55] [RPAK_FSYS] [info] Not loading pak mp_lobby_loadscreen.rpak for dedicated server
[14:14:55] [NORTHSTAR] [info] Registering ConCommand find
[14:14:55] [NORTHSTAR] [info] Registering ConCommand findflags
[14:14:55] [NORTHSTAR] [info] Enabling hook _Host_Map_f_CompletionFunc
[14:14:55] [NORTHSTAR] [info] Enabling hook Host_Map_f
[14:14:55] [NORTHSTAR] [info] CDedicatedExports::RunServer(): starting
[14:14:55] [NORTHSTAR] [info] "Z:\tmp\ns1673676050\NorthstarLauncher.exe" -dedicated -port 37015 +setplaylist aitdm +mp_gamemode aitdm +map mp_grave +ns_private_match_countdown_length 0 +net_compresspackets_minsize 64 +net_compresspackets 1 +spewlog_enable 0 +sv_maxrate 127000 +sv_balanceTeams 1 +sv_cheats 0 -enablechathooks +setplaylist private_match -game R2 -nomenuvid -nosound -windowed -nomessagebox +host_preload_shaders 0 +net_usesocketsforloopback 1 +community_frame_run 0
[14:14:55] [NORTHSTAR] [info] Building KeyValues for file playlists_v2.txt
[14:14:55] [NORTHSTAR] [info] Set playlist to Load a map on the command line
[14:14:55] [NORTHSTAR] [info] Set playlist to Load a map on the command line
[14:14:55] [NORTHSTAR] [info] Set playlist to aitdm
nswrap: northstar exited with status 100
nswrap: killing xvfb
nswrap: waiting for children to exit
~~~~~SNIP~~~~~

**Comment by GeckoEidechse** [comment] 2023-10-03 14:33
Just to confirm, going back to

```
docker pull ghcr.io/pg9182/northstar-dedicated:1-tf2.0.11.0-ns1.19.1
```
does not result in a crash, right?

**Comment by GeckoEidechse** [comment] 2023-10-03 15:10
https://github.com/pg9182/northstar-dedicated-ci/actions/runs/6394806680 also observes this issue, so it must be in launcher code.

**Comment by GeckoEidechse** [comment] 2023-10-03 15:44
https://github.com/pg9182/northstar-dedicated-ci/actions/runs/6395262419 works fine.

This is `v1.19.2` with https://github.com/R2Northstar/NorthstarLauncher/pull/529 reverted, meaning https://github.com/R2Northstar/NorthstarLauncher/pull/529 is the offending commit.

**Comment by GeckoEidechse** [comment] 2023-10-03 20:38
Running the same launch command as in in the initial issue on Windows dedi
```
NorthstarLauncher.exe -dedicated -port 37015 +setplaylist aitdm +mp_gamemode aitdm +map mp_grave +ns_private_match_countdown_length 0 +net_compresspackets_minsize 64 +net_compresspackets 1 +spewlog_enable 0 +sv_maxrate 127000 +sv_balanceTeams 1 +sv_cheats 0 -enablechathooks +setplaylist private_match -game R2 -nomenuvid -nosound -windowed -nomessagebox +host_preload_shaders 0 +net_usesocketsforloopback 1 +community_frame_run 0
```
I cannot reproduce the crash. The server registers just fine. So this is definitely Wine/Docker specific issue IMO.

That being said I still reverted the change upstream for now via https://github.com/R2Northstar/NorthstarLauncher/pull/561, as I do not have the capabilities to debug this and we cannot afford losing Docker support, and I will push out a hotfix soon.

**Comment by GeckoEidechse** [comment] 2023-10-03 21:24
@KallanX should be fixed with the latest Docker image ([`1-tf2.0.11.0-ns1.19.3`](https://github.com/users/pg9182/packages/container/northstar-dedicated/133967413?tag=1-tf2.0.11.0-ns1.19.3)) by reverting a change upstream.

Please retest if you get the change.

I'm gonna leave the issue open still for @pg9182 to see. Maybe he has an idea how to properly fix this in Wine.

**Comment by GeckoEidechse** [comment] 2024-01-02 23:40
Closing as completed via revert and subsequent re-implementation in Northstar with https://github.com/R2Northstar/NorthstarLauncher/pull/564

**Closed by GeckoEidechse** 2024-01-02 23:40 UTC
